#---------------------------------

# Github action push ot docker hub

#---------------------------------

name: Terraform create ec2 instance
run-name: Zuzu mankakan shompayn
on:
  workflow_dispatch:
      inputs:
        environment:
          type: choice
          options:
          - develop
          - production
          default:  develop
jobs:
  terraform-create-instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_KEY }}
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve -input=false -var "env=${{ github.event.inputs.environment }}"